model = "conduction"
sim_name = "ex0"

[mesh]
path = "./meshes/cantilever.msh"

[output]
directory = "../results"

[solver]
max_nonlinear_iters = 4

[materials.beam]
form = "constant"
density = 200.0
specific_heat_capacity = 100.0
conductivity = 100.0

[[boundaries.constraint]]
kind = "isothermal"
temperature = 40.2


[[sources]]
form = "constant"
heat = -12.3
