model = "conduction"
sim_name = "ex0"

[mesh]
path = "./meshes/cantilever.msh"

[output]
directory = "../results"

[[material]]
kind = "builtin:constant_material"
density = 7
conductivity = 10
specific_heat_capacity = 12

[[boundary_condition]]
kind = "builtin:isothermal"
boundaries = ["constraint"]
temperature = 120
