model = "elasticity"
sim_name = "ex1"

[mesh]
path = "./meshes/cantilever.msh"

[output]
directory = "../results"

[[material]]
kind = "builtin:constant_material"
elastic_modulus = 1e11
poissons_ratio = 0.3
density = 7000

[[boundary_condition]]
kind = "builtin:fixed"
boundaries = ["constraint"]
displacement = [0, 0, 0]

[[source]]
kind = "builtin:constant_source"
body_force = [0, 0, -1000]

[fields.displacement]
order = "Quadratic"