# Same as Ex 0 but we see the solution change from the initial conditions
# to the solution we got before.
model = "conduction"
sim_name = "transient_conduction"

[mesh]
path = "./meshes/2d_square.msh"

[output]
directory = "../results"

[time_control]
start = 0
end = 5
timestep = 0.5

[[materials.conduction]]
kind = "builtin:constant_material"
density = 7
conductivity = 10
specific_heat_capacity = 12

[[boundaries.conduction]]
kind = "builtin:isothermal"
boundaries = ["left"]
temperature = 120

[[boundaries.conduction]]
kind = "builtin:isothermal"
boundaries = ["right"]
temperature = 200

[[initial_conditions.conduction]]
kind = "builtin:constant_ic"
temperature = 50

[[sources.conduction]]
kind = "builtin:constant_source"
heat = -1000

