# uses a plugin for a custom source term

model = "conduction"
sim_name = "plugin_sim"

# plugin paths relative to config file
# the plugin source code is in examples/plugins
plugins = ["../.build/my_plug.dll"]

[mesh]
path = "./meshes/cantilever.msh"

[output]
directory = "../results"

[time_control]
start = 0
end = 10
timestep = 0.5

[[sources.conduction]]
kind = "my_plug:custom_source" # use the plugin
frequency = 1.5
amplitude = 1000

[[materials.conduction]]
kind = "builtin:constant_material"
density = 10
conductivity = 10
specific_heat_capacity = 30

[[boundaries.conduction]]
kind = "builtin:isothermal"
boundaries = ["constraint"]
temperature = 40

[[initial_conditions.conduction]]
kind = "builtin:constant_ic"
temperature = 25

