# uses a plugin for a custom source term

model = "conduction"
sim_name = "plugin_sim"

# plugin paths relative to config file
# the plugin source code is in examples/plugins
[[plugins]]
path = "../.build/my_plug.dll"

[mesh]
path = "./meshes/cantilever.msh"

[output]
directory = "../results"

[time_control]
start = 0
end = 10
timestep = 0.5

[[source]]
kind = "my_plug:custom_source" # use the plugin
frequency = 1.5
amplitude = 1000

[[material]]
kind = "builtin:constant_material"
density = 10
conductivity = 10
specific_heat_capacity = 30

[[boundary_condition]]
kind = "builtin:isothermal"
boundaries = ["constraint"]
temperature = 10

[[fields.temperature.initial_conditions]]
kind = "builtin:constant_ic"
temperature = 25

